import maya.cmds as cmds

mop_to_mannequin = {
    'root_M_000_deform': 'root',
    'spine_M_000_deform': 'pelvis',
    'spine_M_001_deform': 'spine_01',
    'spine_M_002_deform': 'spine_02',
    'spine_M_003_deform': 'spine_03',
    'neck_M_000_deform': 'neck_01',
    'head_M_000_deform': 'head',
    'clavicle_L_000_deform': 'clavicle_l',
    'arm_L_shoulder_deform': 'upperarm_l',
    'arm_L_elbow_deform': 'lowerarm_l',
    'arm_L_wrist_deform': 'hand_l',
    'twistUpperArm_L_000_deform': 'upperarm_twist_01_l',
    'twistUpperArm_L_001_deform': 'upperarm_twist_02_l',
    'twistLowerArm_L_000_deform': 'lowerarm_twist_01_l',
    'twistLowerArm_L_001_deform': 'lowerarm_twist_02_l',
    'index_L_000_deform': 'index_01_l',
    'index_L_001_deform': 'index_02_l',
    'index_L_002_deform': 'index_03_l',
    'middle_L_000_deform': 'middle_01_l',
    'middle_L_001_deform': 'middle_02_l',
    'middle_L_002_deform': 'middle_03_l',
    'pinky_L_000_deform': 'pinky_01_l',
    'pinky_L_001_deform': 'pinky_02_l',
    'pinky_L_002_deform': 'pinky_03_l',
    'ring_L_000_deform': 'ring_01_l',
    'ring_L_001_deform': 'ring_02_l',
    'ring_L_002_deform': 'ring_03_l',
    'thumb_L_000_deform': 'thumb_01_l',
    'thumb_L_001_deform': 'thumb_02_l',
    'thumb_L_002_deform': 'thumb_03_l',
    'clavicle_R_000_deform': 'clavicle_r',
    'arm_R_shoulder_deform': 'upperarm_r',
    'arm_R_elbow_deform': 'lowerarm_r',
    'arm_R_wrist_deform': 'hand_r',
    'twistUpperArm_R_000_deform': 'upperarm_twist_01_r',
    'twistUpperArm_R_001_deform': 'upperarm_twist_02_r',
    'twistLowerArm_R_000_deform': 'lowerarm_twist_01_r',
    'twistLowerArm_R_001_deform': 'lowerarm_twist_02_r',
    'index_R_000_deform': 'index_01_r',
    'index_R_001_deform': 'index_02_r',
    'index_R_002_deform': 'index_03_r',
    'middle_R_000_deform': 'middle_01_r',
    'middle_R_001_deform': 'middle_02_r',
    'middle_R_002_deform': 'middle_03_r',
    'pinky_R_000_deform': 'pinky_01_r',
    'pinky_R_001_deform': 'pinky_02_r',
    'pinky_R_002_deform': 'pinky_03_r',
    'ring_R_000_deform': 'ring_01_r',
    'ring_R_001_deform': 'ring_02_r',
    'ring_R_002_deform': 'ring_03_r',
    'thumb_R_000_deform': 'thumb_01_r',
    'thumb_R_001_deform': 'thumb_02_r',
    'thumb_R_002_deform': 'thumb_03_r',
    'leg_L_hip_deform': 'thigh_l',
    'upperLegTwist_L_000_deform': 'thigh_twist_01_l',
    'leg_L_knee_deform': 'calf_l',
    'lowerLegTwist_L_000_deform': 'calf_twist_01_l',
    'leg_L_ankle_deform': 'foot_l',
    'leg_L_foot_ball_deform': 'ball_l',
    'leg_R_hip_deform': 'thigh_r',
    'upperLegTwist_R_000_deform': 'thigh_twist_01_r',
    'leg_R_knee_deform': 'calf_r',
    'lowerLegTwist_R_000_deform': 'calf_twist_01_r',
    'leg_R_ankle_deform': 'foot_r',
    'leg_R_foot_ball_deform': 'ball_r',
}

def run():
    for key, value in mop_to_mannequin.iteritems():
        to_rename = key
        rename_to = value
        if cmds.objExists(to_rename):
            cmds.rename(to_rename, rename_to)


if __name__ == "__main__":
    run()
